provisioning: local
settings:
  artifacts-dir: .bzt/reports
  env:
    REACT_APP_PUBLIC_URL: https://{{project.name}}.bndigital.dev

execution:
  - executor: gatling
    scenario: smoke-test

scenarios:
  smoke-test:
    follow-redirects: true
    requests:
      - ${REACT_APP_PUBLIC_URL}

reporting:
  - module: final-stats

modules:
  gatling:
    version: 3.3.0
  selenium:
    chromedriver:
      version: 89.0.4389.23
      download-link: https://chromedriver.storage.googleapis.com/{version}/chromedriver_{arch}.zip
