name: Analyze
on:
  push:
    paths:
      - .github/workflows/analyze.yml
      - packages/*/src/**/*
    branches:
      - latest

jobs:
  lint:
    name: Lint code
    runs-on: self-hosted
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Install Yarn
        run: npm i -g yarn

      - name: Install dependencies
        run: yarn

      - name: Run linter
        run: yarn lint

  analyze:
    name: Analyze code
    runs-on: self-hosted
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Run Sonar scanner
        uses: kitabisa/sonarqube-action@master
        with:
          host: ${{ secrets.SONARQUBE_HOST }}
          login: ${{ secrets.SONARQUBE_TOKEN }}
