name: Build
on:
  pull_request:
    branches:
      - latest # Will be triggered only on pull request against latest branch with changes in one of paths from below
    paths:
      - ".github/workflows/build.yml"
      - "skaffold.yaml"
      - "**/*/.env.*"
      - "**/*/Dockerfile"
      - "**/*/package.json"
      - "packages/cms/src/**/*"
      - "packages/website/src/**/*"
      - "packages/cms/config/**/*"

env:
  APP_NAME: ${{ github.event.repository.name }} # user for subdomain, docker image repository, Vault path etc
  APP_ENV: staging # used for target infrastructure rollout, Vault path, Kubernetes namespace
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  VAULT_ENDPOINT: ${{ secrets.VAULT_ENDPOINT }}

jobs:
  analyze:
    name: Analyze source code
    runs-on: self-hosted
    steps:
      - name: Checkout sources # Checkout from github
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Import Vault secrets
        uses: hashicorp/vault-action@v2.4.0
        id: secrets
        with:
          method: github
          url: ${{ env.VAULT_ENDPOINT }}
          githubToken: ${{ env.GITHUB_TOKEN }}
          secrets: |
            infrastructure/data/sonarqube url   | SONAR_HOST_URL ;
            infrastructure/data/sonarqube token | SONAR_TOKEN ;

      - name: Run Sonar scanner
        uses: sonarsource/sonarqube-scan-action@v1.0.0
        with:
          args: |
            -Dsonar.projectName=${{ env.APP_NAME }}
            -Dsonar.projectKey=${{ env.APP_NAME }}
            -Dsonar.links.scm=https://github.com/${{ github.repository }}
            -Dsonar.links.ci=https://github.com/${{ github.repository }}/actions

  build:
    name: Build Docker images
    runs-on: self-hosted
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Import Vault secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          method: github
          url: ${{ env.VAULT_ENDPOINT }}
          githubToken: ${{ env.GITHUB_TOKEN }}
          secrets: |
            infrastructure/data/harbor registry     | DOCKER_REGISTRY ;
            infrastructure/data/harbor username     | DOCKER_USERNAME ;
            infrastructure/data/harbor password     | DOCKER_PASSWORD ;
            infrastructure/data/sentry url          | SENTRY_URL ;
            infrastructure/data/sentry organization | SENTRY_ORGANIZATION ;
            infrastructure/data/sentry token        | SENTRY_AUTH_TOKEN ;

      - name: Generate cms .env files
        uses: bn-digital/vault-env@latest
        with:
          endpoint: ${{ env.VAULT_ENDPOINT }}
          token: ${{ env.GITHUB_TOKEN }}
          template: packages/cms/.env.${{ env.APP_ENV }}
          target: packages/cms/.env

      - name: Generate website .env files
        uses: bn-digital/vault-env@latest
        with:
          endpoint: ${{ env.VAULT_ENDPOINT }}
          token: ${{ env.GITHUB_TOKEN }}
          template: packages/website/.env.${{ env.APP_ENV }}
          target: packages/website/.env

      - name: Login Docker registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}/${{ env.APP_NAME }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build Docker images
        uses: hiberbee/github-action-skaffold@1.17.0
        with:
          command: build
          repository: ${{ env.DOCKER_REGISTRY }}/${{ env.APP_NAME }}
          profile: ${{ env.APP_ENV }}