name: CMS
on:
  workflow_dispatch:
    inputs: {}
  push:
    branches:
      - latest
    paths:
      - .github/workflows/cms.yml
      - packages/cms/api/**/*
      - packages/cms/components/**/*
      - packages/cms/config/**/*
      - packages/cms/extensions/**/*
      - packages/cms/package.json

env:
  docker_buildkit: 1
  docker_repository: ${{ secrets.docker_registry }}/app
  docker_image: cms

jobs:
  build:
    name: Build Docker image
    runs-on: self-hosted
    steps:
      - name: Setup builder
        uses: docker/setup-buildx-action@v1

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.docker_registry }}
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: packages/${{ env.docker_image }}
          file: packages/${{ env.docker_image }}/Dockerfile
          cache-from: type=registry,ref=${{ env.docker_repository }}/${{ env.docker_image }}
          cache-to: type=inline
          tags: ${{ env.docker_repository }}/${{ env.docker_image }}:latest

  deploy:
    name: Deploy Helm chart
    needs: [build]
    runs-on: self-hosted
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.digitalocean_token }}

      - name: Save K8S config
        run: doctl kubernetes cluster kubeconfig save ${{ secrets.kubernetes_cluster }} --set-current-context

      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v0.8.0

      - name: Setup Helm diff
        run: helm plugin install https://github.com/databus23/helm-diff

      - name: Helmfile apply
        run: helmfile --environment=staging staging --selector apply
