name: Deploy
on:
  workflow_dispatch: { }
  push:
    branches:
      - latest
    paths:
      - ".github/workflows/deploy.yml"
      - "skaffold.yaml"
      - "**/*/.env.*"
      - "**/*/Dockerfile"
      - "**/*/package.json"
      - "packages/cms/src/**/*"
      - "packages/website/src/**/*"
      - "packages/cms/config/**/*"

env:
  APP_NAME: ${{ github.event.repository.name }}
  APP_ENV: staging
  DOMAIN: ${{ github.event.repository.name }}
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    environment:
      name: staging
      url: https://app.bndigital.dev
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Import Vault secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          method: github
          url: ${{ env.VAULT_ENDPOINT }}
          githubToken: ${{ env.GITHUB_TOKEN }}
          secrets: |
            infrastructure/data/harbor registry     | DOCKER_REGISTRY ;
            infrastructure/data/kubernetes cluster  | KUBERNETES_CLUSTER ;
            infrastructure/data/digitalocean token  | DIGITALOCEAN_TOKEN ;

      - name: Setup DigitalOcean cli
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ env.DIGITALOCEAN_TOKEN }}

      - name: Configure Kubernetes context
        run: doctl kubernetes cluster kubeconfig save ${{ env.KUBERNETES_CLUSTER }} --set-current-context

      - name: Release Helm charts
        uses: hiberbee/github-action-helm@1.10.0
        env:
          APP_VERSION: ${{ env.GITHUB_REF_NAME }}
        with:
          helmfile: apply