---
name: Integration
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    branches:
      - latest
    paths:
      - '.github/workflows/integration.yml'
      - 'skaffold.yaml'
      - 'helmfile.*'
      - '**/*/.env.*'
      - 'Dockerfile'
      - '.dockerignore'
      - 'yarn.lock'
      - 'packages/website/public/**/*'
      - 'packages/website/src/**/*'
      - 'packages/cms/config/**/*'
      - 'packages/cms/src/**/*'
      - 'packages/cms/public/**/*'
      - 'packages/cms/database/**/*'

jobs:
  build:
    needs: [ secrets ]
    uses: bn-digital/docker/.github/workflows/build-images.yml@latest
    secrets: inherit
